create extension if not exists pgcrypto;

create table if not exists public.user_data (
  id text primary key,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.note_shares (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  note_id text not null,
  word_key text not null,
  text text not null,
  likes uuid[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, note_id)
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 5000),
  created_at timestamptz not null default now()
);

alter table public.user_data enable row level security;
alter table public.note_shares enable row level security;
alter table public.feedback enable row level security;

revoke all on table public.user_data, public.note_shares, public.feedback from anon, authenticated;
grant select, insert, update, delete on table public.user_data to authenticated;
grant select, insert, update, delete on table public.note_shares to authenticated;
grant insert on table public.feedback to authenticated;

revoke all on sequence public.feedback_id_seq from anon, authenticated;
grant usage on sequence public.feedback_id_seq to authenticated;

drop policy if exists "shared row for authenticated users" on public.user_data;
drop policy if exists "own row" on public.user_data;
drop policy if exists "users manage own data" on public.user_data;
create policy "users manage own data"
  on public.user_data
  for all
  to authenticated
  using (auth.uid()::text = id)
  with check (auth.uid()::text = id);

drop policy if exists "authenticated users read shared notes" on public.note_shares;
create policy "authenticated users read shared notes"
  on public.note_shares
  for select
  to authenticated
  using (true);

drop policy if exists "users create own shared notes" on public.note_shares;
create policy "users create own shared notes"
  on public.note_shares
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "users update own shared notes" on public.note_shares;
create policy "users update own shared notes"
  on public.note_shares
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "users delete own shared notes" on public.note_shares;
create policy "users delete own shared notes"
  on public.note_shares
  for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "users submit own feedback" on public.feedback;
create policy "users submit own feedback"
  on public.feedback
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create or replace function public.toggle_share_like(p_share_id uuid, p_user_id uuid)
returns uuid[]
language plpgsql
security definer
set search_path = ''
as $$
declare
  updated_likes uuid[];
begin
  if not coalesce(auth.uid() = p_user_id, false) then
    raise exception 'cannot toggle a like for another user'
      using errcode = '42501';
  end if;

  update public.note_shares
  set
    likes = case
      when p_user_id = any(likes) then array_remove(likes, p_user_id)
      else array_append(likes, p_user_id)
    end,
    updated_at = now()
  where id = p_share_id
  returning likes into updated_likes;

  if not found then
    raise exception 'shared note not found'
      using errcode = 'P0002';
  end if;

  return updated_likes;
end;
$$;

revoke all on function public.toggle_share_like(uuid, uuid) from public, anon, authenticated, service_role;
grant execute on function public.toggle_share_like(uuid, uuid) to authenticated;
